### ISSUE TITLE
🪨 📜 ✂️ RPS game

### ISSUE THREAD

**Issue by Zerbaib** [Zerbaib/CleanDiscordBot#5]

**Comment by Zerbaib** [comment]
This nice the command as been created but i have an error:
```
Ignoring exception in slash command 'rps':
Traceback (most recent call last):
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/slash_core.py", line 728, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/params.py", line 1083, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/utils.py", line 567, in maybe_coroutine
    return await value
           ^^^^^^^^^^^
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/cogs/game.py", line 117, in rock_paper_scissors
    await choose_message.add_reaction(emoji)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add_reaction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1378, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/slash_core.py", line 737, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'add_reaction'
```

the code is:
```py
@commands.slash_command(name="rps", description="Play rock-paper-scissors versus the bot.")
    async def rock_paper_scissors(self, ctx):
        choices = {
            0: "Rock",
            1: "Paper",
            2: "Scissors"
        }
        reactions = {
            "🪨": 0,
            "📜": 1,
            "✂️": 2
        }
        embed = disnake.Embed(title="Set your choice, please.")
        embed.color = disnake.Color.blurple()
        embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
        choose_message = await ctx.send(embed=embed)
        for emoji in reactions:
            await choose_message.add_reaction(emoji)

        def check(reaction, user):
            return user == ctx.message.author and str(reaction) in reactions

        try:
            reaction, user = await self.bot.wait_for("reaction_add", timeout=10, check=check)

            user_choice_emote = reaction.emoji
            user_choice_index = reactions[user_choice_emote]

            bot_choice_emote = random.choice(list(reactions.keys()))
            bot_choice_index = reactions[bot_choice_emote]

            result_embed = disnake.Embed()
            result_embed.color = disnake.Color.blurple()
            result_embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
            await choose_message.clear_reactions()

            if user_choice_index == bot_choice_index:
                result_embed.description = f"**It's a tie!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 0 and bot_choice_index == 2:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 1 and bot_choice_index == 0:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 2 and bot_choice_index == 1:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            else:
                result_embed.description = f"**I won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE02B2B
            await choose_message.edit(embed=result_embed)
        except asyncio.exceptions.TimeoutError:
            await choose_message.clear_reactions()
            timeout_embed = disnake.Embed(title="Too late", color=disnake.Color.brand_red())
            timeout_embed.set_author(name=ctx.author.display_name, icon_url=ctx.author.avatar.url)
            await choose_message.edit(embed=timeout_embed)
```
            
my bad

**Comment by Zerbaib** [comment]
# New code
```py
    @commands.slash_command(name="rps", description="Play rock-paper-scissors versus the bot.")
    async def rock_paper_scissors(self, inter: disnake.ApplicationCommandInteraction):
        choices = {
            0: "Rock",
            1: "Paper",
            2: "Scissors"
        }
        reactions = {
            "🪨": 0,
            "📜": 1,
            "✂️": 2
        }
        embed = disnake.Embed(title="Set your choice, please.")
        embed.color = disnake.Color.blurple()
        embed.set_author(name=inter.author.display_name, icon_url=inter.author.avatar.url)

        # Send the initial embed in the interaction response and store the response
        original_response = await inter.respond(embed=embed)

        for emoji in reactions:
            await original_response.add_reaction(emoji)

        def check(reaction, user):
            return user == inter.author and str(reaction) in reactions

        try:
            reaction, user = await self.bot.wait_for("reaction_add", timeout=10, check=check)

            user_choice_emote = reaction.emoji
            user_choice_index = reactions[user_choice_emote]

            bot_choice_emote = random.choice(list(reactions.keys()))
            bot_choice_index = reactions[bot_choice_emote]

            result_embed = disnake.Embed()
            result_embed.color = disnake.Color.blurple()
            result_embed.set_author(name=inter.author.display_name, icon_url=inter.author.avatar.url)

            # Use original_response() here without await
            await original_response.clear_reactions()

            if user_choice_index == bot_choice_index:
                result_embed.description = f"**It's a tie!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 0 and bot_choice_index == 2:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 1 and bot_choice_index == 0:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            elif user_choice_index == 2 and bot_choice_index == 1:
                result_embed.description = f"**You won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE8C02A
            else:
                result_embed.description = f"**I won!**\nYou chose {user_choice_emote} and I chose {bot_choice_emote}."
                result_embed.colour = 0xE02B2B

            # Use original_response() here without await
            await original_response.edit(embed=result_embed)
        except asyncio.exceptions.TimeoutError:
            # Use original_response() here without await
            await original_response.clear_reactions()
            timeout_embed = disnake.Embed(title="Too late", color=disnake.Color.brand_red())
            timeout_embed.set_author(name=inter.author.display_name, icon_url=inter.author.avatar.url)

            # Use original_response() here without await
            await original_response.edit(embed=timeout_embed)
```
            
The error:

```
Ignoring exception in slash command 'rps':
Traceback (most recent call last):
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/slash_core.py", line 728, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/params.py", line 1083, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/utils.py", line 567, in maybe_coroutine
    return await value
           ^^^^^^^^^^^
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/cogs/game.py", line 119, in rock_paper_scissors
    original_response = await inter.respond(embed=embed)
                              ^^^^^^^^^^^^^
AttributeError: 'ApplicationCommandInteraction' object has no attribute 'respond'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1378, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/hugo/Documents/code/Zerbaib/CleanDiscordBot/.venv/lib/python3.11/site-packages/disnake/ext/commands/slash_core.py", line 737, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ApplicationCommandInteraction' object has no attribute 'respond'
```
